# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 727807d909769c9e025d381005f5fe025eafc82a2343079efa89b3bbd460a81b1f727ebeaa8036f3beff817de8219054e9fff47734d4333aa45dea7fc9783a4d

test:
  secret_key_base: c60096e5652d39b4a833630a6f7b0044925f92cb6310d563e62f00ac4cb7083a26d1c5dc76b08820a61aba5806c04e16ca044c9ef09807eebbff1f33d21a5ed9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
